# This workflow will build a package using Maven and then publish it to GitHub packages
# whenever code is pushed or a pull request is created.

name: Maven Package

# Trigger the workflow on every push and pull request
on:
  push:
    branches:
      - main    # You can specify other branches here, or use `*` for all branches.
  pull_request:
    branches:
      - main    # Run on pull requests targeting the main branch.

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact to release
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jar
        path: target/*.jar
